CREATE DATABASE FARMACIA;

USE FARMACIA;

CREATE TABLE MEDICAMENTOS(
    IDMEDICAMENTO INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    TARJA VARCHAR(15) NOT NULL,
    VALIDADE DATE NOT NULL,
    FABRICACAO DATE NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL
);

CREATE TABLE CLIENTES(
    IDCLIENTE INT NOT NULL PRIMARY KEY,
    CPF VARCHAR(16) UNIQUE NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    DATANASC DATE NOT NULL,
    APOSENTADO BOOLEAN NOT NULL,
    SEXO CHAR
);

CREATE TABLE USUARIOS(
    IDUSUARIO INT NOT NULL PRIMARY KEY,
    USUARIO VARCHAR(20) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    TIPOUSER BOOLEAN NOT NULL
);

CREATE TABLE CAIXAS(
    IDCAIXA INT NOT NULL PRIMARY KEY,
    VALORINICIAL DECIMAL(10,2) NOT NULL,
    DATAABERTURA DATETIME NOT NULL,
    VALORFINAL DECIMAL(10,2),
    DATAFECHAMENTO DATETIME,
    STATUSCX BOOLEAN
);

CREATE TABLE VENDAS(
    IDVENDA INT NOT NULL PRIMARY KEY,
    DATAVENDA DATETIME NOT NULL,
    VALORTOTAL DECIMAL(10,2),
    TIPOPAG VARCHAR(12),
    FK_IDCLIENTE INT,
    FOREIGN KEY (FK_IDCLIENTE) REFERENCES CLIENTES(IDCLIENTE) 
);

CREATE TABLE VENDASMED(
    IDVENDASMED INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FK_IDVENDA INT,
    FK_IDMEDICAMENTO INT,
    FOREIGN KEY (FK_IDVENDA) REFERENCES VENDAS(IDVENDA),
    FOREIGN KEY (FK_IDMEDICAMENTO) REFERENCES MEDICAMENTOS(IDMEDICAMENTO) 
);