/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Venda;

import Caixa.CaixaDAO;
import Medicamento.Medicamento;
import Medicamento.MedicamentoDAO;
import Views.menuPrincipal;
import static Views.menuPrincipal.cli;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wellington
 */
public class menuVendas extends javax.swing.JFrame {
    private Venda venda = new Venda();
    private MedicamentoDAO dbMed = new MedicamentoDAO();
    /**
     * Creates new form menuVendas
     */
    public menuVendas() {
        initComponents();
        try{
            txtValorTotal.setText("0");
            addLinhaTabela();
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,"Falha ao preencher a tabela");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMeds = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        txtCpf = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmbTipoPag = new javax.swing.JComboBox<>();
        lblDescApos = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblDescDin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescAposentado = new javax.swing.JLabel();
        txtDescDinheiro = new javax.swing.JLabel();
        txtQtd = new javax.swing.JLabel();
        btnConcede = new javax.swing.JButton();
        btnFinaliza = new javax.swing.JButton();
        txtValorTotal = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCarrinho = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        txtTipoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(29, 131, 72));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setBackground(new java.awt.Color(29, 131, 72));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));

        tbMeds.setBackground(new java.awt.Color(29, 131, 72));
        tbMeds.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbMeds.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        tbMeds.setForeground(new java.awt.Color(240, 240, 240));
        tbMeds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "TARJA", "PREÇO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMeds.setGridColor(new java.awt.Color(40, 189, 99));
        jScrollPane1.setViewportView(tbMeds);

        lblNome.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(240, 240, 240));
        lblNome.setText("Cliente:");

        txtCpf.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        txtCpf.setForeground(new java.awt.Color(240, 240, 240));
        txtCpf.setText("Não encontrado");

        txtNome.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        txtNome.setForeground(new java.awt.Color(240, 240, 240));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.fw.png"))); // NOI18N
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(29, 131, 72));

        cmbTipoPag.setBackground(new java.awt.Color(29, 131, 72));
        cmbTipoPag.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        cmbTipoPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cartão", "Dinheiro" }));

        lblDescApos.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblDescApos.setForeground(new java.awt.Color(240, 240, 240));
        lblDescApos.setText("Desconto aposentado: R$");

        lblValor.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lblValor.setForeground(new java.awt.Color(240, 240, 240));
        lblValor.setText("Valor Total: R$");

        lblDescDin.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblDescDin.setForeground(new java.awt.Color(240, 240, 240));
        lblDescDin.setText("Desconto em dinheiro: R$");

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Quantidade de Itens:");

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Tipo de Pagamento:");

        txtDescAposentado.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        txtDescAposentado.setForeground(new java.awt.Color(240, 240, 240));
        txtDescAposentado.setText("0.00");

        txtDescDinheiro.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        txtDescDinheiro.setForeground(new java.awt.Color(240, 240, 240));
        txtDescDinheiro.setText("0.00");

        txtQtd.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        txtQtd.setForeground(new java.awt.Color(240, 240, 240));
        txtQtd.setText("0");

        btnConcede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/concederDesconto.fw.png"))); // NOI18N
        btnConcede.setContentAreaFilled(false);
        btnConcede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConcede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcedeActionPerformed(evt);
            }
        });

        btnFinaliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/finalizarVenda.fw.png"))); // NOI18N
        btnFinaliza.setContentAreaFilled(false);
        btnFinaliza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtValorTotal.setFont(new java.awt.Font("Open Sans", 0, 22)); // NOI18N
        txtValorTotal.setForeground(new java.awt.Color(240, 240, 240));
        txtValorTotal.setText("0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDescApos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescAposentado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescDin)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnConcede, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescDinheiro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtd)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lblValor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtValorTotal)
                            .addGap(22, 22, 22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnFinaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQtd, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValorTotal))
                .addGap(30, 30, 30)
                .addComponent(btnFinaliza)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTipoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescApos)
                    .addComponent(txtDescAposentado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescDin)
                    .addComponent(txtDescDinheiro))
                .addGap(18, 18, 18)
                .addComponent(btnConcede)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/remove.fw.png"))); // NOI18N
        btnRemove.setContentAreaFilled(false);
        btnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/carrinhoHeader.fw.png"))); // NOI18N

        jScrollPane2.setBackground(new java.awt.Color(29, 131, 72));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 2));

        tbCarrinho.setBackground(new java.awt.Color(29, 131, 72));
        tbCarrinho.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        tbCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "TARJA", "PREÇO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbCarrinho);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/medicamentosHeader2.fw.png"))); // NOI18N

        lblNome1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(240, 240, 240));
        lblNome1.setText("CPF:");

        lblNome2.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lblNome2.setForeground(new java.awt.Color(240, 240, 240));
        lblNome2.setText("Tipo de cliente:");

        txtTipoCliente.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        txtTipoCliente.setForeground(new java.awt.Color(240, 240, 240));
        txtTipoCliente.setText("NA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(151, 151, 151))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(202, 202, 202))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTipoCliente)
                        .addComponent(lblNome2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNome)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf)
                    .addComponent(lblNome1))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtNome.setText(menuPrincipal.cli.getNome());
        txtCpf.setText(menuPrincipal.cli.getCpf());
        if (!menuPrincipal.cli.isAposentado()){
            lblDescApos.setText("Desconto Aposentado:");
            txtDescAposentado.setText("Não Aplicável");
            txtTipoCliente.setText("Comum");
        }
        else{
            lblDescDin.setText("Desconto em dinheiro:");
            txtDescDinheiro.setText("Não Aplicável");
            txtTipoCliente.setText("Aposentado");
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbCarrinho.getModel();
        // get selected row index
        try {
            int SelectedRowIndex = tbCarrinho.getSelectedRow();
            subtraiValorTotal();
            model.removeRow(SelectedRowIndex);
            preencheQtd();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Selecione algum item para remover!");
            return;
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            int aux = (int)tbMeds.getValueAt(tbMeds.getSelectedRow(), 0);
            somaValorTotal();
            addLinhaCarrinho(aux);
            preencheQtd();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(menuVendas.class.getName()).log(Level.SEVERE, null, ex);
        } catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Selecione um item para adicionar!");
            return;
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnConcedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcedeActionPerformed
        try {
            double valorAtual;
            double desconto;
            JOptionPane.showMessageDialog(null, "É necessário informar as credenciais do gerente para conceder o desconto!");
            String user = JOptionPane.showInputDialog(null, "Digite o nome de usuário: ");
            String pass = JOptionPane.showInputDialog(null, "Digite a senha: ");
            CaixaDAO dbCx = new CaixaDAO();
            if(dbCx.checkGerente(user,pass)){
                valorAtual = Double.valueOf(txtValorTotal.getText());
                //se for aposentado da desconto
                if(menuPrincipal.cli.isAposentado()){
                    desconto = Double.valueOf(txtDescAposentado.getText());
                    valorAtual -= desconto;
                    txtValorTotal.setText(String.valueOf(valorAtual));
                }
                else{
                    if (cmbTipoPag.getSelectedIndex()==1){                        
                        desconto = Double.valueOf(txtDescDinheiro.getText());
                        txtValorTotal.setText(String.valueOf(valorAtual));
                    }
                }
                JOptionPane.showMessageDialog(null,"Desconto Concedido com sucesso!");
            }                
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Credencias invalidas");
            return;
        }
    }//GEN-LAST:event_btnConcedeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnConcede;
    private javax.swing.JButton btnFinaliza;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbTipoPag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescApos;
    private javax.swing.JLabel lblDescDin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tbCarrinho;
    private javax.swing.JTable tbMeds;
    private javax.swing.JLabel txtCpf;
    private javax.swing.JLabel txtDescAposentado;
    private javax.swing.JLabel txtDescDinheiro;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtQtd;
    private javax.swing.JLabel txtTipoCliente;
    private javax.swing.JLabel txtValorTotal;
    // End of variables declaration//GEN-END:variables
    //preenchendo tabela
    public void addLinhaTabela() throws ClassNotFoundException, SQLException{
        DefaultTableModel model = (DefaultTableModel) tbMeds.getModel();
        ArrayList<Medicamento> lstMeds = dbMed.listar("");
        Object infoLinha [] = new Object[4];
        for (int i=0; i<lstMeds.size(); i++){
            infoLinha[0] = lstMeds.get(i).getIdMed();
            infoLinha[1] = lstMeds.get(i).getNome();
            infoLinha[2] = lstMeds.get(i).getTarja();
            infoLinha[3] = lstMeds.get(i).getPreco();
            model.addRow(infoLinha);
        }
    }
    //preenchendo tabela
    public void addLinhaCarrinho(int aux) throws ClassNotFoundException, SQLException{
        DefaultTableModel model = (DefaultTableModel) tbCarrinho.getModel();
        //gambiarra pra concatenar o criterio da query
        String aux2 = "IDMEDICAMENTO="+String.valueOf(aux);
        ArrayList<Medicamento> lstMeds = dbMed.listar(aux2);
        Object infoLinha [] = new Object[4];
        for (int i=0; i<lstMeds.size(); i++){
            infoLinha[0] = lstMeds.get(i).getIdMed();
            infoLinha[1] = lstMeds.get(i).getNome();
            infoLinha[2] = lstMeds.get(i).getTarja();
            infoLinha[3] = lstMeds.get(i).getPreco();
            model.addRow(infoLinha);
        }
    }
    
    public void preencheQtd(){
        int qtd = tbCarrinho.getRowCount();
        txtQtd.setText(String.valueOf(qtd));
    }
    
    //somando valor total pra jogar no banco depois
    public void somaValorTotal(){
        double valorTotal;
        double vlComum;
        double vlAposentado;
        double valorNew = (double)tbMeds.getValueAt(tbMeds.getSelectedRow(),3);
        double valorAtual = Double.valueOf(txtValorTotal.getText());
        valorTotal = valorAtual + valorNew;
        DecimalFormat formato = new DecimalFormat("#.##", new DecimalFormatSymbols(Locale.US));      
        valorTotal = Double.valueOf(formato.format(valorTotal));
        txtValorTotal.setText(String.valueOf(valorTotal));
        if (menuPrincipal.cli.isAposentado()){
            vlAposentado = valorTotal * 0.2;
            vlAposentado = Double.valueOf(formato.format(vlAposentado));
            txtDescAposentado.setText(String.valueOf(vlAposentado));
        }
        else{
            vlComum = valorTotal * 0.05;
            vlComum = Double.valueOf(formato.format(vlComum));
            txtDescDinheiro.setText(String.valueOf(vlComum));
        }
    }
    
    //subtraindo valor total pra jogar no banco    
    public void subtraiValorTotal(){
        double valorTotal;
        double vlComum;
        double vlAposentado;
        double valorNew = (double)tbMeds.getValueAt(tbMeds.getSelectedRow(),3);
        double valorAtual = Double.valueOf(txtValorTotal.getText());
        valorTotal = valorAtual - valorNew;
        DecimalFormat formato = new DecimalFormat("#.##", new DecimalFormatSymbols(Locale.US));      
        valorTotal = Double.valueOf(formato.format(valorTotal));
        txtValorTotal.setText(String.valueOf(valorTotal));
        if (menuPrincipal.cli.isAposentado()){
            vlAposentado = valorTotal * 0.2;
            vlAposentado = Double.valueOf(formato.format(vlAposentado));
            txtDescAposentado.setText(String.valueOf(vlAposentado));
        }
        else{
            vlComum = valorTotal * 0.05;
            vlComum = Double.valueOf(formato.format(vlComum));
            txtDescDinheiro.setText(String.valueOf(vlComum));
        }
    }
    
}
